sources:
  - name: Countries
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com
    transforms:
      - federation:
          types:
            - name: Query
              config:
                extend: true
            - name: Country
              config:
                keyFields:
                  - code
  - name: CartQL
    handler:
      graphql:
        endpoint: https://api.cartql.com
    transforms:
      - federation:
          types:
            - name: Query
              config:
                extend: true
            - name: Cart
              config:
                keyFields:
                  - id
documents:
  - example-query.graphql

serve:
  playground: true
